/* Alle Spiele aller vier Mannschaften. Aus nuLiga, Stand 16.09.2026.
   Wird von der wöchentlichen Aufgabe fortgeschrieben. */
window.VEREINSSPIELE = {
 "verein": "Charlottenburger TSV",
 "saison": "2026/27",
 "abgerufen": "2026-09-16",
 "quelle": "nuLiga BVBB, Gruppen I=41956, II=42121, III=42137, IV=42155",
 "mannschaften": [
  {
   "kurz": "I",
   "liga": "C-Klasse 1",
   "gruppe": 41956
  },
  {
   "kurz": "II",
   "liga": "D-Klasse 2",
   "gruppe": 42121
  },
  {
   "kurz": "III",
   "liga": "F-Klasse 2",
   "gruppe": 42137
  },
  {
   "kurz": "IV",
   "liga": "G-Klasse 1",
   "gruppe": 42155
  }
 ],
 "spiele": [
  {
   "mannschaft": "I",
   "liga": "C-Klasse 1",
   "tag": "Sa",
   "datum": "2026-09-26",
   "datumDe": "26.09.2026",
   "zeit": "12:30",
   "halle": "TU",
   "daheim": false,
   "verlegt": false,
   "gegner": "PSV Berlin II"
  },
  {
   "mannschaft": "III",
   "liga": "F-Klasse 2",
   "tag": "So",
   "datum": "2026-09-27",
   "datumDe": "27.09.2026",
   "zeit": "10:00",
   "halle": "DE",
   "daheim": false,
   "verlegt": false,
   "gegner": "TuS Lichterfelde II"
  },
  {
   "mannschaft": "IV",
   "liga": "G-Klasse 1",
   "tag": "So",
   "datum": "2026-09-27",
   "datumDe": "27.09.2026",
   "zeit": "15:00",
   "halle": "BD",
   "daheim": false,
   "verlegt": false,
   "gegner": "Köpenicker BC VIII"
  },
  {
   "mannschaft": "II",
   "liga": "D-Klasse 2",
   "tag": "Mi",
   "datum": "2026-09-30",
   "datumDe": "30.09.2026",
   "zeit": "19:30",
   "halle": "KF",
   "daheim": true,
   "verlegt": false,
   "gegner": "Deutsch-Chinesischer BV II"
  },
  {
   "mannschaft": "II",
   "liga": "D-Klasse 2",
   "tag": "Do",
   "datum": "2026-10-01",
   "datumDe": "01.10.2026",
   "zeit": "19:00",
   "halle": "AD",
   "daheim": false,
   "verlegt": false,
   "gegner": "Vorspiel QSB"
  },
  {
   "mannschaft": "I",
   "liga": "C-Klasse 1",
   "tag": "Do",
   "datum": "2026-10-01",
   "datumDe": "01.10.2026",
   "zeit": "19:30",
   "halle": "KF",
   "daheim": true,
   "verlegt": false,
   "gegner": "RSV Eintracht"
  },
  {
   "mannschaft": "III",
   "liga": "F-Klasse 2",
   "tag": "Do",
   "datum": "2026-10-01",
   "datumDe": "01.10.2026",
   "zeit": "19:30",
   "halle": "KF",
   "daheim": true,
   "verlegt": false,
   "gegner": "SG Petershagen/Germania III"
  },
  {
   "mannschaft": "IV",
   "liga": "G-Klasse 1",
   "tag": "Mo",
   "datum": "2026-10-05",
   "datumDe": "05.10.2026",
   "zeit": "18:30",
   "halle": "HP",
   "daheim": false,
   "verlegt": false,
   "gegner": "SV Glienicke (Brandenburg)"
  },
  {
   "mannschaft": "IV",
   "liga": "G-Klasse 1",
   "tag": "Mi",
   "datum": "2026-10-07",
   "datumDe": "07.10.2026",
   "zeit": "19:30",
   "halle": "KF",
   "daheim": true,
   "verlegt": false,
   "gegner": "RSV Eintracht (Brandenburg) IV"
  },
  {
   "mannschaft": "II",
   "liga": "D-Klasse 2",
   "tag": "Mi",
   "datum": "2026-11-04",
   "datumDe": "04.11.2026",
   "zeit": "19:30",
   "halle": "KF",
   "daheim": true,
   "verlegt": true,
   "gegner": "DIBVM V"
  },
  {
   "mannschaft": "I",
   "liga": "C-Klasse 1",
   "tag": "Do",
   "datum": "2026-11-05",
   "datumDe": "05.11.2026",
   "zeit": "19:30",
   "halle": "KF",
   "daheim": true,
   "verlegt": false,
   "gegner": "VfB Hermsdorf IV"
  },
  {
   "mannschaft": "III",
   "liga": "F-Klasse 2",
   "tag": "Do",
   "datum": "2026-11-05",
   "datumDe": "05.11.2026",
   "zeit": "19:30",
   "halle": "KF",
   "daheim": true,
   "verlegt": false,
   "gegner": "Pro Sport (Berlin) VI"
  },
  {
   "mannschaft": "III",
   "liga": "F-Klasse 2",
   "tag": "Sa",
   "datum": "2026-11-07",
   "datumDe": "07.11.2026",
   "zeit": "10:30",
   "halle": "LY",
   "daheim": false,
   "verlegt": false,
   "gegner": "TSV Wedding II"
  },
  {
   "mannschaft": "IV",
   "liga": "G-Klasse 1",
   "tag": "So",
   "datum": "2026-11-08",
   "datumDe": "08.11.2026",
   "zeit": "17:00",
   "halle": "UR",
   "daheim": false,
   "verlegt": false,
   "gegner": "VSG Altglienicke (Berlin) II"
  },
  {
   "mannschaft": "I",
   "liga": "C-Klasse 1",
   "tag": "Mo",
   "datum": "2026-11-09",
   "datumDe": "09.11.2026",
   "zeit": "19:30",
   "halle": "GE",
   "daheim": false,
   "verlegt": false,
   "gegner": "Märkischer SC II"
  },
  {
   "mannschaft": "IV",
   "liga": "G-Klasse 1",
   "tag": "Mi",
   "datum": "2026-11-11",
   "datumDe": "11.11.2026",
   "zeit": "19:30",
   "halle": "KF",
   "daheim": true,
   "verlegt": false,
   "gegner": "VSG Rahnsdorf III"
  },
  {
   "mannschaft": "II",
   "liga": "D-Klasse 2",
   "tag": "Sa",
   "datum": "2026-11-14",
   "datumDe": "14.11.2026",
   "zeit": "18:30",
   "halle": "KF",
   "daheim": true,
   "verlegt": false,
   "gegner": "SG Gaselan Fürstenwalde II"
  },
  {
   "mannschaft": "IV",
   "liga": "G-Klasse 1",
   "tag": "Sa",
   "datum": "2026-11-14",
   "datumDe": "14.11.2026",
   "zeit": "18:30",
   "halle": "KF",
   "daheim": true,
   "verlegt": false,
   "gegner": "BSV Werder (Brandenburg) III"
  },
  {
   "mannschaft": "I",
   "liga": "C-Klasse 1",
   "tag": "Do",
   "datum": "2026-11-19",
   "datumDe": "19.11.2026",
   "zeit": "19:30",
   "halle": "KF",
   "daheim": true,
   "verlegt": false,
   "gegner": "VfB Kiefholz VIII"
  },
  {
   "mannschaft": "III",
   "liga": "F-Klasse 2",
   "tag": "Do",
   "datum": "2026-11-19",
   "datumDe": "19.11.2026",
   "zeit": "19:30",
   "halle": "KF",
   "daheim": true,
   "verlegt": false,
   "gegner": "VSG Altglienicke"
  },
  {
   "mannschaft": "II",
   "liga": "D-Klasse 2",
   "tag": "So",
   "datum": "2026-11-22",
   "datumDe": "22.11.2026",
   "zeit": "10:00",
   "halle": "DI",
   "daheim": false,
   "verlegt": false,
   "gegner": "SG BC Tempelhof/Friedenau V"
  },
  {
   "mannschaft": "I",
   "liga": "C-Klasse 1",
   "tag": "So",
   "datum": "2026-11-29",
   "datumDe": "29.11.2026",
   "zeit": "10:00",
   "halle": "PD",
   "daheim": false,
   "verlegt": false,
   "gegner": "SV Motor Eberswalde"
  },
  {
   "mannschaft": "III",
   "liga": "F-Klasse 2",
   "tag": "So",
   "datum": "2026-11-29",
   "datumDe": "29.11.2026",
   "zeit": "10:00",
   "halle": "FX",
   "daheim": false,
   "verlegt": false,
   "gegner": "TSV Tempelhof-Mariendorf IV"
  },
  {
   "mannschaft": "II",
   "liga": "D-Klasse 2",
   "tag": "Mi",
   "datum": "2026-12-02",
   "datumDe": "02.12.2026",
   "zeit": "19:30",
   "halle": "KF",
   "daheim": true,
   "verlegt": false,
   "gegner": "TuS Lichterfelde"
  },
  {
   "mannschaft": "IV",
   "liga": "G-Klasse 1",
   "tag": "Mi",
   "datum": "2026-12-02",
   "datumDe": "02.12.2026",
   "zeit": "19:30",
   "halle": "KF",
   "daheim": true,
   "verlegt": false,
   "gegner": "SV Berliner Bären III"
  },
  {
   "mannschaft": "III",
   "liga": "F-Klasse 2",
   "tag": "Do",
   "datum": "2026-12-10",
   "datumDe": "10.12.2026",
   "zeit": "19:30",
   "halle": "KF",
   "daheim": true,
   "verlegt": false,
   "gegner": "DIBVM VI"
  },
  {
   "mannschaft": "II",
   "liga": "D-Klasse 2",
   "tag": "Sa",
   "datum": "2026-12-12",
   "datumDe": "12.12.2026",
   "zeit": "10:00",
   "halle": "TM",
   "daheim": false,
   "verlegt": false,
   "gegner": "SV Berliner Brauereien VIII"
  },
  {
   "mannschaft": "IV",
   "liga": "G-Klasse 1",
   "tag": "Sa",
   "datum": "2026-12-12",
   "datumDe": "12.12.2026",
   "zeit": "17:00",
   "halle": "SO",
   "daheim": false,
   "verlegt": false,
   "gegner": "VfB Kiefholz (Berlin) XII"
  },
  {
   "mannschaft": "I",
   "liga": "C-Klasse 1",
   "tag": "Sa",
   "datum": "2026-12-12",
   "datumDe": "12.12.2026",
   "zeit": "18:30",
   "halle": "KF",
   "daheim": true,
   "verlegt": false,
   "gegner": "BSV Werder II"
  },
  {
   "mannschaft": "IV",
   "liga": "G-Klasse 1",
   "tag": "Mi",
   "datum": "2027-01-06",
   "datumDe": "06.01.2027",
   "zeit": "19:30",
   "halle": "KF",
   "daheim": true,
   "verlegt": false,
   "gegner": "Köpenicker BC VIII"
  },
  {
   "mannschaft": "I",
   "liga": "C-Klasse 1",
   "tag": "Do",
   "datum": "2027-01-07",
   "datumDe": "07.01.2027",
   "zeit": "19:30",
   "halle": "KF",
   "daheim": true,
   "verlegt": false,
   "gegner": "PSV Berlin II"
  },
  {
   "mannschaft": "III",
   "liga": "F-Klasse 2",
   "tag": "Do",
   "datum": "2027-01-07",
   "datumDe": "07.01.2027",
   "zeit": "19:30",
   "halle": "KF",
   "daheim": true,
   "verlegt": false,
   "gegner": "TuS Lichterfelde II"
  },
  {
   "mannschaft": "II",
   "liga": "D-Klasse 2",
   "tag": "Fr",
   "datum": "2027-01-08",
   "datumDe": "08.01.2027",
   "zeit": "19:30",
   "halle": "TU",
   "daheim": false,
   "verlegt": false,
   "gegner": "Deutsch-Chinesischer BV II"
  },
  {
   "mannschaft": "IV",
   "liga": "G-Klasse 1",
   "tag": "Sa",
   "datum": "2027-01-16",
   "datumDe": "16.01.2027",
   "zeit": "11:00",
   "halle": "IK",
   "daheim": false,
   "verlegt": false,
   "gegner": "RSV Eintracht (Brandenburg) IV"
  },
  {
   "mannschaft": "I",
   "liga": "C-Klasse 1",
   "tag": "Sa",
   "datum": "2027-01-16",
   "datumDe": "16.01.2027",
   "zeit": "14:00",
   "halle": "IK",
   "daheim": false,
   "verlegt": false,
   "gegner": "RSV Eintracht"
  },
  {
   "mannschaft": "III",
   "liga": "F-Klasse 2",
   "tag": "So",
   "datum": "2027-01-17",
   "datumDe": "17.01.2027",
   "zeit": "10:00",
   "halle": "EL",
   "daheim": false,
   "verlegt": false,
   "gegner": "SG Petershagen/Germania III"
  },
  {
   "mannschaft": "II",
   "liga": "D-Klasse 2",
   "tag": "Mi",
   "datum": "2027-01-20",
   "datumDe": "20.01.2027",
   "zeit": "19:30",
   "halle": "KF",
   "daheim": true,
   "verlegt": false,
   "gegner": "Vorspiel QSB"
  },
  {
   "mannschaft": "IV",
   "liga": "G-Klasse 1",
   "tag": "Mi",
   "datum": "2027-01-20",
   "datumDe": "20.01.2027",
   "zeit": "19:30",
   "halle": "KF",
   "daheim": true,
   "verlegt": false,
   "gegner": "SV Glienicke (Brandenburg)"
  },
  {
   "mannschaft": "III",
   "liga": "F-Klasse 2",
   "tag": "Do",
   "datum": "2027-01-21",
   "datumDe": "21.01.2027",
   "zeit": "19:30",
   "halle": "KF",
   "daheim": true,
   "verlegt": false,
   "gegner": "TSV Wedding II"
  },
  {
   "mannschaft": "I",
   "liga": "C-Klasse 1",
   "tag": "Sa",
   "datum": "2027-01-23",
   "datumDe": "23.01.2027",
   "zeit": "17:30",
   "halle": "HE",
   "daheim": false,
   "verlegt": false,
   "gegner": "VfB Hermsdorf IV"
  },
  {
   "mannschaft": "IV",
   "liga": "G-Klasse 1",
   "tag": "So",
   "datum": "2027-01-24",
   "datumDe": "24.01.2027",
   "zeit": "11:00",
   "halle": "WE",
   "daheim": false,
   "verlegt": false,
   "gegner": "BSV Werder (Brandenburg) III"
  },
  {
   "mannschaft": "II",
   "liga": "D-Klasse 2",
   "tag": "So",
   "datum": "2027-01-24",
   "datumDe": "24.01.2027",
   "zeit": "12:30",
   "halle": "RA",
   "daheim": false,
   "verlegt": true,
   "gegner": "DIBVM V"
  },
  {
   "mannschaft": "IV",
   "liga": "G-Klasse 1",
   "tag": "Mi",
   "datum": "2027-02-10",
   "datumDe": "10.02.2027",
   "zeit": "19:30",
   "halle": "KF",
   "daheim": true,
   "verlegt": false,
   "gegner": "VSG Altglienicke (Berlin) II"
  },
  {
   "mannschaft": "I",
   "liga": "C-Klasse 1",
   "tag": "Do",
   "datum": "2027-02-11",
   "datumDe": "11.02.2027",
   "zeit": "19:30",
   "halle": "KF",
   "daheim": true,
   "verlegt": false,
   "gegner": "Märkischer SC II"
  },
  {
   "mannschaft": "III",
   "liga": "F-Klasse 2",
   "tag": "Sa",
   "datum": "2027-02-13",
   "datumDe": "13.02.2027",
   "zeit": "13:00",
   "halle": "EZ",
   "daheim": false,
   "verlegt": false,
   "gegner": "Pro Sport (Berlin) VI"
  },
  {
   "mannschaft": "IV",
   "liga": "G-Klasse 1",
   "tag": "Sa",
   "datum": "2027-02-13",
   "datumDe": "13.02.2027",
   "zeit": "13:00",
   "halle": "FU",
   "daheim": false,
   "verlegt": false,
   "gegner": "VSG Rahnsdorf III"
  },
  {
   "mannschaft": "I",
   "liga": "C-Klasse 1",
   "tag": "So",
   "datum": "2027-02-14",
   "datumDe": "14.02.2027",
   "zeit": "10:00",
   "halle": "HG",
   "daheim": false,
   "verlegt": false,
   "gegner": "VfB Kiefholz VIII"
  },
  {
   "mannschaft": "III",
   "liga": "F-Klasse 2",
   "tag": "So",
   "datum": "2027-02-14",
   "datumDe": "14.02.2027",
   "zeit": "15:00",
   "halle": "UR",
   "daheim": false,
   "verlegt": false,
   "gegner": "VSG Altglienicke"
  },
  {
   "mannschaft": "II",
   "liga": "D-Klasse 2",
   "tag": "Mi",
   "datum": "2027-02-17",
   "datumDe": "17.02.2027",
   "zeit": "19:30",
   "halle": "KF",
   "daheim": true,
   "verlegt": false,
   "gegner": "SG BC Tempelhof/Friedenau V"
  },
  {
   "mannschaft": "II",
   "liga": "D-Klasse 2",
   "tag": "So",
   "datum": "2027-02-21",
   "datumDe": "21.02.2027",
   "zeit": "10:00",
   "halle": "ED",
   "daheim": false,
   "verlegt": false,
   "gegner": "SG Gaselan Fürstenwalde II"
  },
  {
   "mannschaft": "III",
   "liga": "F-Klasse 2",
   "tag": "Do",
   "datum": "2027-03-04",
   "datumDe": "04.03.2027",
   "zeit": "19:30",
   "halle": "KF",
   "daheim": true,
   "verlegt": false,
   "gegner": "TSV Tempelhof-Mariendorf IV"
  },
  {
   "mannschaft": "IV",
   "liga": "G-Klasse 1",
   "tag": "Sa",
   "datum": "2027-03-06",
   "datumDe": "06.03.2027",
   "zeit": "12:00",
   "halle": "AV",
   "daheim": false,
   "verlegt": false,
   "gegner": "SV Berliner Bären III"
  },
  {
   "mannschaft": "I",
   "liga": "C-Klasse 1",
   "tag": "Sa",
   "datum": "2027-03-06",
   "datumDe": "06.03.2027",
   "zeit": "18:30",
   "halle": "KF",
   "daheim": true,
   "verlegt": false,
   "gegner": "SV Motor Eberswalde"
  },
  {
   "mannschaft": "II",
   "liga": "D-Klasse 2",
   "tag": "So",
   "datum": "2027-03-07",
   "datumDe": "07.03.2027",
   "zeit": "10:00",
   "halle": "DE",
   "daheim": false,
   "verlegt": false,
   "gegner": "TuS Lichterfelde"
  },
  {
   "mannschaft": "II",
   "liga": "D-Klasse 2",
   "tag": "Mi",
   "datum": "2027-03-17",
   "datumDe": "17.03.2027",
   "zeit": "19:30",
   "halle": "KF",
   "daheim": true,
   "verlegt": false,
   "gegner": "SV Berliner Brauereien VIII"
  },
  {
   "mannschaft": "IV",
   "liga": "G-Klasse 1",
   "tag": "Mi",
   "datum": "2027-03-17",
   "datumDe": "17.03.2027",
   "zeit": "19:30",
   "halle": "KF",
   "daheim": true,
   "verlegt": false,
   "gegner": "VfB Kiefholz (Berlin) XII"
  },
  {
   "mannschaft": "III",
   "liga": "F-Klasse 2",
   "tag": "So",
   "datum": "2027-03-21",
   "datumDe": "21.03.2027",
   "zeit": "12:30",
   "halle": "RA",
   "daheim": false,
   "verlegt": true,
   "gegner": "DIBVM VI"
  },
  {
   "mannschaft": "I",
   "liga": "C-Klasse 1",
   "tag": "So",
   "datum": "2027-03-21",
   "datumDe": "21.03.2027",
   "zeit": "14:00",
   "halle": "WE",
   "daheim": false,
   "verlegt": false,
   "gegner": "BSV Werder II"
  }
 ]
};
